changelog-seen = 2

[llvm]
targets = "X86"
experimental-targets = ""

[build]
build = "x86_64-pc-windows-msvc"

# host = ["x86_64-unknown-linux-gnu"]

target = ["i586-oldpc-windows-msvc", "i686-oldpc-windows-msvc", "x86_64-pc-windows-msvc"]

[install]

[rust]
incremental = true

[target.i586-oldpc-windows-msvc]

[target.i686-oldpc-windows-msvc]

[dist]
